language: node_js

os:
  - linux

node_js:
  - '10'
  - '12'

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - npm install -g yarn

install:
  - yarn install

script:
  - yarn build
