language: node_js
os:
  - linux
cache:
  yarn: true

stages:
  - name: deploy
    if: type = push AND branch = dev
  - name: PR review
    if: type = pull_request

jobs:
  include:
    - stage: PR review
      env:
        - PR_DEMO_REPO: github.com/trendmicro-frontend/styled-ui-demo.git
        - PR_DEMO_SITE: https://trendmicro-frontend.github.io/styled-ui-demo
        - secure: "1hJgtxxGQdVerHK673tRbUWO4UAwdT0U1qwDpNGVCr/7vbnxcTpbLuexmdxpP3ORk4UOS8ZGZclEcnscpH/2t+qgkDNk5Y+6DGFb5Av3eIcDyltfr4eZuWo+olNlGCE3GgZJReJWDnBQM8/9pf3nUhFlG7VN7p+I/254J2FKpatGWv+aJvcBRzAu403SzYECVxtG/wIkvnl8GN9xjRVSbLYD1MuqZnWt3bnPj8NqdR+yaQSmLPzLE+5j43/noNn1BdBQ6I/bgEw37n9lxUj5BSLNDss/YElW0CynrFXgPCwYXWK0uhw4Vf7xL9JJ8OpJqkVmtx4lqAS39su6gjZW+gCb2pzrV29BGmYQJ5CUcMb8qKENAKBSV8uyBwsF30d4WWU0oi/wrsl6Oc/5GvXJbRTVBG2oHXuYScMUIhMqvNntfqPZ/uKKSqPUkXMY9B8f6kzRM2SmKqD+3NdO2QoLhUbiBBVXJVRhygKACDZLrgS8SDCuJarWVI5rs6LQxHbOzKxOgLrh5nlOzGO3yTFTKoM00JV9RMBrCjg2wRQNfHx3tPXlUo2a6O5A88rfIFfUJ066nYH2zXlyCO6crmuENa4H7/1nzYditiHFjg7hPr0630Zru1qPCbRElvCh9gelKBIC+gsG6uCcWRpx7VyVEP3LNagmBhDRQMVwvSD7ln4="
      node_js:
        - '10'
      before_install:
        - npm install -g yarn
      install:
        - yarn global add octokit-cli
        - yarn install
        - yarn test
        - yarn list --silent react react-dom
      script:
        - yarn build
        - yarn pre-push
      after_success:
        - git clone "https://${GH_TOKEN}@${PR_DEMO_REPO}" styled-ui-demo > /dev/null 2>&1
        - cd styled-ui-demo
        - git checkout gh-pages
        - git pull "https://${GH_TOKEN}@${PR_DEMO_REPO}" gh-pages > /dev/null 2>&1
        - git rm -rf pr-${TRAVIS_PULL_REQUEST}
        - mkdir -p pr-${TRAVIS_PULL_REQUEST}
        - cp -af ../packages/styled-docs/docs/** pr-${TRAVIS_PULL_REQUEST}/
        - git add pr-${TRAVIS_PULL_REQUEST}
        - git commit -m "added pr-${TRAVIS_PULL_REQUEST} by ${TRAVIS_PULL_REQUEST_SLUG}"
        - git push "https://${GH_TOKEN}@${PR_DEMO_REPO}" gh-pages > /dev/null 2>&1
        - cd ..
        - octokit issues create-comment --body "Successfully deployed ${TRAVIS_COMMIT} to ${PR_DEMO_SITE}/pr-${TRAVIS_PULL_REQUEST}" --owner trendmicro-frontend --repo styled-ui --issue_number ${TRAVIS_PULL_REQUEST}
    - stage: deploy
      node_js:
        - '10'
      before_install:
        - npm install -g yarn
      install:
        - yarn install
        - yarn test
        - yarn list --silent react react-dom
      script:
        - yarn build
        - yarn pre-push
      after_success: true
      deploy:
        provider: pages:git
        edge: true # dpl v2
        token:
          secure: "EDPLwCPAyG6QGtWRpCmZrs+2t/mX4a0V2ng/ImbhBorpiAfgG9RBMs14454A4qr11xGneeh8khcGZ06egeStBsyzeYc59PGGDHwuhygpOzEgNGLJsldsDJQ0/WmDiAhKQHeUcHO3Ck/2EqILChX3mJBq4zsiuZw5U05AhnXw0RTnLQf0vAAcPKQllZ/pgdbi+nRNZugBpVOc+SoSp9hX+yy01CGXwrWo+MSzgtJl3xrn6k7mZZmyviY0DQE0JMfZsv3kOx1y8JT9F2aXd51aH0rPSBzO8AjWFAhSAenE0mz0sMqDmonDOYGVIHy9jnTBpy9i/E1NuZ4PHM472W2APbuxZA1U3L3e/6ATIx1BQYPGu2uM3DqSbTTtyLZoWXY8rdsA3PQuaeje3XzlQ2fbTSBbN/230GrjtLwKNugvTIRvf3JTaxKn83SUICrrzq0ChDAffNn5AEv7V95Q7ykX1UfDHFs2uhKYDTM9ITeWhPFkm6wDqcqQeu3cxMOLmrMWtwDlLu0VEtIIvZWYEjXxnFYo8E2e34lqn0j1aQEWqpznC+pJ9Rrpajs0dHO3U1dkSWvEli/Z7NmfdQ15MR0J1X/zLbLuPBR+7pT9qRVMC0XU58oky2eEUZ0kDmGAgLLDSynEGxK2JUHcsTBIhXeqaW4rDbT+GOhzGuOgh/sHaBs="
        keep_history: false
        target_branch: gh-pages
        local_dir: "packages/styled-docs/docs"
        on:
          branch: dev
          node: '10'

notifications:
  slack:
    secure: dPF2omw9ykWqJ2C9kV8yq67zJVyezt58kmnRHavrq1+U1e5tDZootxoMjwMzq/T3pctghLbE4QYtg4s3GxINP5mMLMKLoUjDqsnFijKXB9jInWdbxFcDi0pY1w3KimEgSUWd5UZS6WWH23mPGO923KKhu3FE0jnISNlpV6/HQAiAgokMYEMC3Sx9V37iUQsnVBpshhEHMXbK6s9kp6H1gmmfPNuqnSJN0PQ9OaRKlUOlbFjgahFJdljG/TG1qeeGGxUzGu+r1tBmsfsjSqgWbcRDNfHpkx1PeelyhorsA6/CMBW82tVAGA5Z03nw0USrETG8vqPm/B6nnAa+vCvXaUxeft0R75Dczmx9FqGNygyrIwbtxjel5BQCYovVxjkHDniOhd7n0I7c97aXkaaJTvSV2CRSt7DmOPiNE+6mqBaEh9f7OfjsTA8/nShsaVQ5DQAuGfxsSjRTDuJY5NGjBgfIF/2nT2gS1cS/QQza6HcijaOWKTRCgT6/PC++oNTTy6FK1H7epYe41HmIYCDF/Urk1k+DlmCSbshdIGRg05anuTLqCPi6Tz7fFKNNzY4uuB6315vDgKOI91JTIM+5QBCgxjm09E2eIiEpZgIEicvjs1CKZIsfi9R1HgkWD+mngcJvYApwQ+qwvdV/L+zLUkWR9ifz3uFIFtssK30OWQ8=
